Ripasso di loop

In [ ]:
frase = "questo cane è più veloce di un altro cane"

# Questi sono equivalenti

for parola in frase.split():
    print(parola)

lista_parole = frase.split()
for i in range(len(lista_parole)):
    print(lista_parole[i])

ii = 0
while ii < len(lista_parole):
    print(lista_parole[ii])
    ii += 1

In [ ]:
conta = 0
for parola in frase.split():
    if parola == "cane":
        conta += 1

print(conta)

2


In [ ]:
ast = '*'
#con un loop creare una piramide di asterischi di lughezza massima 4:
# *
# **
# ***
# ****
# ***
# **
# *
for i in range(4):
    print(ast*(i+1))
for i in range(3,0,-1):
    print(ast*i)

*
**
***
****
***
**
*


In [ ]:
 #creare una lista con tutti i numeri da 1 a 20 con un while loop

lista_numeri = []
n = 1
while len(lista_numeri) < 20:
    lista_numeri.append(n)
    n+=1

print(lista_numeri)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [ ]:
#per leggere e rimuovere da una lista possiamo usare lista.pop()
#partendo da lista_numeri, con un while loop creare una lista invertita

lista_numeri_inv = []
while len(lista_numeri) > 0:
    numero = lista_numeri.pop()
    lista_numeri_inv.append(numero)

print(lista_numeri_inv)

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
lista_numeri_inv2= []
dim = len(lista_numeri)
i=1
while len(lista_numeri_inv2) <20:
    n = lista_numeri[dim-i]
    lista_numeri_inv2.append(n)
    i += 1

print(lista_numeri_inv2)

In [ ]:
lista_numeri_inv3= []
i=-1 #prende dall'ultimo elemento
while len(lista_numeri_inv3) <20:
    n = lista_numeri[i]
    lista_numeri_inv3.append(n)
    i -= 1 #N.B. riduco di uno

print(lista_numeri_inv3)

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
#fare la somma tra indici delle due liste
print(lista_numeri)
print(lista_numeri_inv3)

conta = 0
lista_sommata = []
while len(lista_numeri) > conta and len(lista_numeri_inv3) > conta:
    s = lista_numeri[conta] + lista_numeri_inv3[conta]
    lista_sommata.append(s)
    conta +=1

print(lista_sommata)

lista_sommata.clear()
for elemento1, elemento2 in zip(lista_numeri, lista_numeri_inv3):
    lista_sommata.append(elemento1+elemento2)

print(lista_sommata)

lista_sommata.clear()
for i in range(min(len(lista_numeri), len(lista_numeri_inv3))):
    s = lista_numeri[i] + lista_numeri_inv3[i]
    lista_sommata.append(s)

print(lista_sommata)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21]
[21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21]
[21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21]


In [ ]:
#fattoriale:
# 5! = 5*4*3*2*1
# 0! = 1

#dato un numero (fornito dall'utente (input)), calcolare il fattoriale (con un loop)
numero = int(input("calcola il fattoriale di: "))
n = numero
risultato = 1
while n > 0:
    risultato = risultato * n
    n -= 1

print(risultato)

numero = int(input("calcola il fattoriale di: "))

if n == 0 or n==1:
    risultato = 1
elif n<0:
    risultato = "nosipuò"
else:
    risultato =1
    for i in range(1, n+1):
        risultato *= i

print(risultato)

120
120


In [ ]:
def fattoriale_con_ricorsione(n):
    if n < 0:
        return "errore"
    elif n < 2:
        return 1
    else:
        return n * fattoriale_con_ricorsione(n-1)
    

numero = int(input("calcola il fattoriale di: "))
fattoriale_con_ricorsione(numero)

6689502913449127057588118054090372586752746333138029810295671352301633557244962989366874165271984981308157637893214090552534408589408121859898481114389650005964960521256960000000000000000000000000000

In [ ]:
import math
math.factorial(5)

In [ ]:
import numpy as np
array_di_numeri = np.array(lista_numeri)
array_di_numeri_inv = np.array(lista_numeri_inv3)

lista_sommata.clear()
for i in range(min(len(array_di_numeri), len(array_di_numeri_inv))):
    s = array_di_numeri[i] + array_di_numeri_inv[i]
    lista_sommata.append(s)

print(np.array(lista_sommata))

print(array_di_numeri + array_di_numeri_inv)

[21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21]
[21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21]


In [ ]:
array2D_a_caso = np.linspace(0,100,100).reshape((10,10))

forma = array2D_a_caso.shape #questo è un tuple

for i in range(forma[0]):
    for j in range(forma[1]):
        print(array2D_a_caso[i][j])# uguale a array[i,j]

0.0
1.0101010101010102
2.0202020202020203
3.0303030303030303
4.040404040404041
5.050505050505051
6.0606060606060606
7.070707070707071
8.080808080808081
9.090909090909092
10.101010101010102
11.111111111111112
12.121212121212121
13.131313131313131
14.141414141414142
15.151515151515152
16.161616161616163
17.171717171717173
18.181818181818183
19.191919191919194
20.202020202020204
21.212121212121215
22.222222222222225
23.232323232323235
24.242424242424242
25.252525252525253
26.262626262626263
27.272727272727273
28.282828282828284
29.292929292929294
30.303030303030305
31.313131313131315
32.323232323232325
33.333333333333336
34.343434343434346
35.35353535353536
36.36363636363637
37.37373737373738
38.38383838383839
39.3939393939394
40.40404040404041
41.41414141414142
42.42424242424243
43.43434343434344
44.44444444444445
45.45454545454546
46.46464646464647
47.47474747474748
48.484848484848484
49.494949494949495
50.505050505050505
51.515151515151516
52.525252525252526
53.535353535353536
54.54545

# Knight's Walk

esempio tratto da 
https://www.youtube.com/watch?v=RGQe8waGJ4w (runtime: 6:12)

## Parte I : Initilizzazione della scacchiera

Ci servirà una matrice a 2 dimensioni. La matrice avrà dimensioni $(2n+1)*(2n+1)$, con n = numero intero (int)

La scacchiera avrà centro con coordinate (n,n).

Riempiamo l'array con numeri interi e a spirale. Ad esempio:
```python
board = initialize_board(3)
```

il risultato sarà:
```julia
7×7 Array{Int64,2}:
 37  36  35  34  33  32  31
 38  17  16  15  14  13  30
 39  18   5   4   3  12  29
 40  19   6   1   2  11  28
 41  20   7   8   9  10  27
 42  21  22  23  24  25  26
 43  44  45  46  47  48  49
```

*Note:*
- Python usa indici con base 0, il centro dell'array `board` è l'elemento `board[n,n]`, non `board[0,0]`
- Dopo aver trovato il centro, inserendo il valore 1, dobbiamo considerare esattamente $n$ "Cerchi" di raggio maggiore. Useremo un for-loop.
- In ogni cerchio, ci sono 4 segmenti (su, sinistra, giù, destra) che possiamo gestire con 4 for-loops
.

In [30]:
import numpy as np

def initialize_board(n):
    dim_board = 2*n + 1
    board = np.zeros((dim_board, dim_board), dtype=int)

    board[n,n] = 1

    i=2

    #per ogni cerchio: (for)
    for circle in range(1, n+1):
        #esempio di come fare:
        # board[n,n+circle] = i
        # i += 1
        #riempi segmento destro (for)
        for dx in range(n+circle-1, n-circle-1, -1):
            board[dx, n+circle] = i
            i += 1
        #riempi segmento superiore (for)
        for sp in range(n+circle, n-circle, -1):
            board[n-circle, sp-1] = i
            i += 1        
        #riempi segmento sinistro (for)
        for sx in range(n-circle, n+circle):
            board[sx+1, n-circle] = i
            i += 1
        #riempi segmento inferiore (for)
        for ip in range(n-circle, n+circle):
            board[n+circle, ip+1] = i
            i += 1

    return board

In [31]:
initialize_board(2)

array([[17, 16, 15, 14, 13],
       [18,  5,  4,  3, 12],
       [19,  6,  1,  2, 11],
       [20,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

## Parte 2 - Simulare i salti

Dobbiamo simulare e creare la sequenza numerica.

Ci serve un'altra funzione che come input prenderà il nostro `board`.
Questa funzione ci restituirà la sequenza e (dopo) le coordinate x e y

Esempio di codice:
```python
board = initialize_board(2)
seq, xs, ys = simulate_walk(board)
print("Sequence = ", seq)
print("x-coordinates = ", xs)
print("y-coordinates = ", ys)
```

Risultato:
```julia
5×5 Array{Int64,2}:
 17  16  15  14  13
 18   5   4   3  12
 19   6   1   2  11
 20   7   8   9  10
 21  22  23  24  25
Sequence = [1, 10, 3, 6, 9, 4, 7, 2, 5, 8, 11, 14]
```

*Consigli:*
- usare un array per indicare se il riquadro è stato visitato (bool)
- attenzione a non far uscire il cavallo dalla scacchiera


In [34]:
def simulate_walk(board):
    sequenza = []
    board_size = np.size(board, 0)
    visited = np.zeros((board_size,board_size), dtype=bool)
    center = board_size//2
    x, y = center, center

    visited[x,y] = True
    sequenza.append(board[x,y])

    # loop per trovare il resto della sequenza
    dead = False
    while not dead:
        dead = True

    return sequenza

In [35]:
board = initialize_board(2)
simulate_walk(board)

[1]

In [ ]:
#DA COMPLETARE