# Knight's Walk

esempio tratto da 
https://www.youtube.com/watch?v=RGQe8waGJ4w (runtime: 6:12)

## Parte I : Initilizzazione della scacchiera

Ci servirà una matrice a 2 dimensioni. La matrice avrà dimensioni $(2n+1)*(2n+1)$, con n = numero intero (int)

La scacchiera avrà centro con coordinate (n,n).

Riempiamo l'array con numeri interi e a spirale. Ad esempio:
```python
board = initialize_board(3)
```

il risultato sarà:
```julia
7×7 Array{Int64,2}:
 37  36  35  34  33  32  31
 38  17  16  15  14  13  30
 39  18   5   4   3  12  29
 40  19   6   1   2  11  28
 41  20   7   8   9  10  27
 42  21  22  23  24  25  26
 43  44  45  46  47  48  49
```

*Note:*
- Python usa indici con base 0, il centro dell'array `board` è l'elemento `board[n,n]`, non `board[0,0]`
- Dopo aver trovato il centro, inserendo il valore 1, dobbiamo considerare esattamente $n$ "Cerchi" di raggio maggiore. Useremo un for-loop.
- In ogni cerchio, ci sono 4 segmenti (su, sinistra, giù, destra) che possiamo gestire con 4 for-loops
.

In [30]:
import numpy as np

def initialize_board(n):
    dim_board = 2*n + 1
    board = np.zeros((dim_board, dim_board), dtype=int)

    board[n,n] = 1

    i=2

    #per ogni cerchio: (for)
    for circle in range(1, n+1):
        #esempio di come fare:
        # board[n,n+circle] = i
        # i += 1
        #riempi segmento destro (for)
        for dx in range(n+circle-1, n-circle-1, -1):
            board[dx, n+circle] = i
            i += 1
        #riempi segmento superiore (for)
        for sp in range(n+circle, n-circle, -1):
            board[n-circle, sp-1] = i
            i += 1        
        #riempi segmento sinistro (for)
        for sx in range(n-circle, n+circle):
            board[sx+1, n-circle] = i
            i += 1
        #riempi segmento inferiore (for)
        for ip in range(n-circle, n+circle):
            board[n+circle, ip+1] = i
            i += 1

    return board

In [31]:
initialize_board(2)

array([[17, 16, 15, 14, 13],
       [18,  5,  4,  3, 12],
       [19,  6,  1,  2, 11],
       [20,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

## Parte 2 - Simulare i salti

Dobbiamo simulare e creare la sequenza numerica.

Ci serve un'altra funzione che come input prenderà il nostro `board`.
Questa funzione ci restituirà la sequenza e (dopo) le coordinate x e y

Esempio di codice:
```python
board = initialize_board(2)
seq, xs, ys = simulate_walk(board)
print("Sequence = ", seq)
print("x-coordinates = ", xs)
print("y-coordinates = ", ys)
```

Risultato:
```julia
5×5 Array{Int64,2}:
 17  16  15  14  13
 18   5   4   3  12
 19   6   1   2  11
 20   7   8   9  10
 21  22  23  24  25
Sequence = [1, 10, 3, 6, 9, 4, 7, 2, 5, 8, 11, 14]
```

*Consigli:*
- usare un array per indicare se il riquadro è stato visitato (bool)
- attenzione a non far uscire il cavallo dalla scacchiera


In [34]:
def simulate_walk(board):
    sequenza = []
    board_size = np.size(board, 0)
    visited = np.zeros((board_size,board_size), dtype=bool)
    center = board_size//2
    x, y = center, center

    visited[x,y] = True
    sequenza.append(board[x,y])

    # loop per trovare il resto della sequenza
    dead = False
    while not dead:
        dead = True

    return sequenza

In [35]:
board = initialize_board(2)
simulate_walk(board)

[1]